const dummyData = [
    {
      "end_year": 2018,
      "intensity": 12,
      "sector": "Information Technology",
      "topic": "artificial intelligence",
      "insight": "What's next for Health IT - Trends for 2018",
      "url": "http://www.infosysblogs.com/healthcare/2017/06/whats_next_for_health_it_tre.html",
      "start_year": 2017,
      "added": "June 26, 2018 07:28:39",
      "published": "June 26, 2018 00:00:00",
      "relevance": 3,
      "pestle": "Technological",
      "source": "infosysblogs",
      "title": "Adoption of AI diagnostics is expected to further accelerate through 2017-18.",
      "likelihood": 4
    },
    {
      "end_year": 2020,
      "intensity": 16,
      "topic": "pharmaceutical",
      "insight": "The 8 Healthcare Trends that will impact your sales in 2018",
      "url": "http://www.jhconline.com/the-8-healthcare-trends-that-will-impact-your-salesin-2018.html",
      "start_year": 2010,
      "impact": 3,
      "added": "June 26, 2018 05:53:45",
      "published": "June 26, 2018 00:00:00",
      "relevance": 4,
      "pestle": "Healthcare",
      "title": "The Specialty Pharma market was $274 billion in 2010 and will be $483 billion in 2020.",
      "likelihood": 4
    },
    {
      "end_year": 2024,
      "intensity": 20,
      "sector": "Pharmaceuticals",
      "topic": "drug",
      "insight": "Market share of top 20 companies for orphan drugs worldwide 2017 and 2024",
      "url": "https://www.statista.com/statistics/373373/top-companies-based-on-globalorphan-drug-market-share/",
      "region": "World",
      "added": "June 26, 2018 03:53:23",
      "published": "June 26, 2018 00:00:00",
      "relevance": 5,
      "pestle": "Healthcare",
      "source": "Statista Infographics",
      "title": "In 2017, Roche's orphan drugs market share accounted for 8.2 percent of the world's market and is expected to decrease down to 5.2 percent by 2024.",
      "likelihood": 4
    },
    {
      "end_year": 2019,
      "intensity": 16,
      "sector": "Information Technology",
      "topic": "data",
      "insight": "New NASA mission to detect plant water use from space",
      "url": "https://climate.nasa.gov/news/2752/new-nasa-mission-to-detect-plant-wateruse-from-space/",
      "region": "World",
      "added": "June 26, 2018 06:50:48",
      "published": "June 26, 2018 00:00:00",
      "relevance": 4,
      "pestle": "Technological",
      "source": "Climate Change: Vital Signs of the Planet",
      "title": "Over the next year, ECOSTRESS will use the space station's unique low Earth orbit to collect data over multiple areas of land at different times of day.",
      "likelihood": 4
    },
    {
      "end_year": 2020,
      "intensity": 12,
      "topic": "organization",
      "insight": "Cylance Extends AI-Driven Security to Hybrid Environments and Private Networks With CylanceHYBRID and CylanceON-PREM",
      "url": "http://www.cybersecuritytrend.com/news/2018/06/21/8776300.htm",
      "added": "June 26, 2018 02:59:51",
      "published": "June 26, 2018 00:00:00",
      "relevance": 3,
      "pestle": "Organization",
      "source": "Cybersecurity Trend",
      "title": "90 percent of organizations will adopt hybrid strategies by 2020.",
      "likelihood": 4
    }
  ];
  export default dummyData;